In [27]:
%matplotlib notebook
import numpy, pickle
data = pickle.load(open('../../../Xharecost_MS_annex/plot_data_DELETE.pkl','rb'))
#data = pickle.load(open('../../../Xharecost_MS_annex/plot_data.pkl','rb'))
COEFF_ARRAY_INTERNAL_COINS = data['COEFF_ARRAY_INTERNAL_COINS']
coin_flip_params_dict = data['coin_flip_params_dict']
profits_given_coeffs = data['profits_given_coeffs']
no_COIN_FLIPS = data['no_COIN_FLIPS']
instance_base = data['instance_base']
coin_flip_biases_dict = data['coin_flip_biases_dict']
print "DELETE VERSION"

In [28]:
for coeff_no,coeff_internal in enumerate(COEFF_ARRAY_INTERNAL_COINS):
    print profits_given_coeffs[coeff_no]['people_count_dict']['additional_people']

[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  1.   1.   0.   0.   1.   0.   0.   0.   1.   1.]
 [  2.   1.   3.   2.   2.   3.   1.   0.   2.   5.]
 [  3.   2.   7.   4.   5.   7.   7.   2.   6.   5.]
 [  6.   6.   9.   7.   7.  11.  12.   5.   8.   8.]
 [  9.   9.  14.   9.   9.  12.  13.   6.  10.  11.]]
[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  1.   1.   0.   0.   0.   1.   0.   0.   0.   1.]
 [  3.   2.   3.   0.   0.   2.   1.   2.   2.   4.]
 [  6.   3.   9.   6.   3.   8.   6.   3.  10.   5.]
 [  8.   6.  17.  16.   8.  12.  14.  10.  15.   9.]
 [ 17.  14.  23.  24.  14.  19.  18.  19.  20.  12.]
 [ 22.  21.  30.  30.  22.  29.  20.  24.  32.  20.]]
[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   1.   0.   1.   1.   0.   0.   0.]
 [  5.   8.   5.   4.   4.   1.   4.   2.   3.   3.]
 [  9.   9.  12.   8.  10.  10.   8.   9.  10.  10.]
 [ 16.  17.  15.  14.  14.  20.  16.  16.  1