In [16]:
%matplotlib notebook
import numpy, pickle
#data = pickle.load(open('../../../Xharecost_MS_annex/plot_data_DELETE.pkl','rb'))
#print "DELETE VERSION"
data = pickle.load(open('../../../Xharecost_MS_annex/plot_data.pkl','rb'))
COEFF_ARRAY_INTERNAL_COINS = data['COEFF_ARRAY_INTERNAL_COINS']
coin_flip_params_dict = data['coin_flip_params_dict']
profits_given_coeffs = data['profits_given_coeffs']
no_COIN_FLIPS = data['no_COIN_FLIPS']
instance_base = data['instance_base']
coin_flip_biases_dict = data['coin_flip_biases_dict']


In [18]:
for coeff_no,coeff_internal in enumerate(COEFF_ARRAY_INTERNAL_COINS):
    #print profits_given_coeffs[coeff_no]['people_count_dict']['additional_people']
    print numpy.median(profits_given_coeffs[coeff_no]['people_count_dict']['additional_people'],axis=1)

[ 0.  0.  0.  2.  4.  6.  9.]
[  0.    0.    2.    5.5  11.   17.   23. ]
[  0.   0.   3.   9.  17.  25.  33.]
[  0.   0.   3.  12.  21.  31.  41.]
[  0.   1.  10.  26.  42.  56.  64.]


In [22]:
#people_pct = numpy.zeros(len(COEFF_ARRAY_INTERNAL_COINS),len())
for coeff_no,coeff_internal in enumerate(COEFF_ARRAY_INTERNAL_COINS):
    temp = profits_given_coeffs[coeff_no]['people_count_dict']['additional_people_pct']
    print numpy.median(temp,axis=1)

[ 0.    0.    0.    0.08  0.16  0.24  0.36]
[ 0.    0.    0.08  0.22  0.44  0.68  0.92]
[ 0.    0.    0.12  0.36  0.68  1.    1.32]
[ 0.    0.    0.12  0.48  0.84  1.24  1.64]
[ 0.    0.04  0.4   1.04  1.68  2.24  2.56]


In [21]:
for coeff_no,coeff_internal in enumerate(COEFF_ARRAY_INTERNAL_COINS):
    temp1  = numpy.median(profits_given_coeffs[coeff_no]['total_profit_array'],axis=1)
    print temp1 - temp1[0]

[    0.         -2088.26204314 -2088.26204314 -1805.73547096 -3073.12058489
 -3740.26809343 -4467.71046484]
[    0.         -2088.26204314 -1413.95104953   274.72347781  -297.78803237
  -656.06879105 -1974.92936118]
[    0.         -2088.26204314 -1167.34988655  1286.66907682  1760.58542262
  1145.26212424     4.4411007 ]
[    0.         -2088.26204314  -406.09707596  2671.02484879  2553.84371381
  1835.94543132   473.70332674]
[    0.         -2088.26204314  3078.01908488  7753.4848268   7928.466227
  5748.62562266  4389.06893384]


In [ ]:
temp1[0,0]